# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FSRmsg.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='FSRmsg.proto',
  package='pyFSRray',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x46SRmsg.proto\x12\x08pyFSRray\"6\n\x07\x46SRData\x12\x0b\n\x03\x66sr\x18\x01 \x01(\t\x12\x0b\n\x03\x61\x63\x63\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\"@\n\x06\x46SRMsg\x12\x11\n\tsensor_id\x18\x01 \x01(\x05\x12#\n\x08\x66sr_data\x18\x02 \x03(\x0b\x32\x11.pyFSRray.FSRDatab\x06proto3'
)




_FSRDATA = _descriptor.Descriptor(
  name='FSRData',
  full_name='pyFSRray.FSRData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='fsr', full_name='pyFSRray.FSRData.fsr', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='acc', full_name='pyFSRray.FSRData.acc', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='pyFSRray.FSRData.timestamp', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=80,
)


_FSRMSG = _descriptor.Descriptor(
  name='FSRMsg',
  full_name='pyFSRray.FSRMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sensor_id', full_name='pyFSRray.FSRMsg.sensor_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fsr_data', full_name='pyFSRray.FSRMsg.fsr_data', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=146,
)

_FSRMSG.fields_by_name['fsr_data'].message_type = _FSRDATA
DESCRIPTOR.message_types_by_name['FSRData'] = _FSRDATA
DESCRIPTOR.message_types_by_name['FSRMsg'] = _FSRMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FSRData = _reflection.GeneratedProtocolMessageType('FSRData', (_message.Message,), {
  'DESCRIPTOR' : _FSRDATA,
  '__module__' : 'FSRmsg_pb2'
  # @@protoc_insertion_point(class_scope:pyFSRray.FSRData)
  })
_sym_db.RegisterMessage(FSRData)

FSRMsg = _reflection.GeneratedProtocolMessageType('FSRMsg', (_message.Message,), {
  'DESCRIPTOR' : _FSRMSG,
  '__module__' : 'FSRmsg_pb2'
  # @@protoc_insertion_point(class_scope:pyFSRray.FSRMsg)
  })
_sym_db.RegisterMessage(FSRMsg)


# @@protoc_insertion_point(module_scope)
